In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [4]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

# np.zeros or np.ones also creates arrays

In [5]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## RANDOM

In [7]:
np.random.rand(5)

array([0.91187863, 0.802313  , 0.25726367, 0.93633309, 0.42904609])

In [8]:
np.random.rand(5,2)

array([[0.11943763, 0.95786712],
       [0.89787575, 0.1759314 ],
       [0.69892358, 0.34909024],
       [0.37954717, 0.80731809],
       [0.37954288, 0.22089263]])

In [9]:
np.random.randint(0, 101, 10)

array([61,  2, 54, 47, 62,  8, 38, 68, 42,  8])

## Setting seed allows us to get same results

In [10]:
np.random.seed(100)
np.random.rand(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

  ## Modifying shapes

In [11]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
ranarr = np.random.randint(0,101,10)

In [14]:
ranarr

array([ 98,  53,  66,  98,  14,  34,  24,  15, 100,  60])

In [15]:
ranarr.max()

100

In [16]:
ranarr.min()

14

In [17]:
ranarr.argmax()

8

In [18]:
ranarr.dtype

dtype('int32')

In [19]:
ranarr.shape

(10,)

# TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/ea9c4d2fc6c98ac74af18134cd924867
# import ?
# myarray = ?

In [20]:
myarray = np.linspace(0,10, 101)

In [21]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

## SLICING AND SELECTION

In [24]:
sel_arr = np.arange(0,11)

In [25]:
sel_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
sel_arr[8]


8

In [28]:
sel_arr[1:5]

array([1, 2, 3, 4])

In [29]:
sel_arr[0:5]

array([0, 1, 2, 3, 4])

In [30]:
sel_arr[:5]

array([0, 1, 2, 3, 4])

In [31]:
sel_arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [33]:
sel_arr[0:5] = 100
sel_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
sel_arr = np.arange(0,11)

In [35]:
slice_of_arr = sel_arr[0:5]

In [36]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [37]:
slice_of_arr[:] = 99

In [38]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [39]:
sel_arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## IMPORTANT, VALUES ARE BROADCASTED, WHEN SLICING ARRAY IT JUST POINTS TO MEMORY, TO COPY VALUES WITHOUT THEIR ADDRESS COPY EXPLICITLY, LIKE BELOW


In [40]:
arr_copy = sel_arr[0:5].copy()
arr_copy

array([99, 99, 99, 99, 99])

In [41]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100])

In [42]:
sel_arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### 2d ARRAYS

In [44]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

In [45]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [46]:
arr_2d.shape #ROWS, COLUMNS

(3, 3)

In [47]:
arr_2d[0]

array([ 5, 10, 15])

In [48]:
arr_2d[1,1]

25

In [49]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# CONDITIONS ON ARRAYS

In [51]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [54]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [56]:
arr[arr>6]

array([ 7,  8,  9, 10])

## NUMPY OPERATIONS

In [57]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
arr + arr # must be same shape

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
arr2d.sum()

300

## TO PERFORM OPERATIONS ON SINGLE ROW/COL set axis parameter. axis = 0 - row , axis = 1 = cols.  ACROSS - meaning when 0 it goes top -> bottom, when 1 it goes left -> right

In [62]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [63]:
arr2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])