In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [4]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

# np.zeros or np.ones also creates arrays

In [5]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## RANDOM

In [7]:
np.random.rand(5)

array([0.90988685, 0.61549922, 0.28249753, 0.59531806, 0.02085796])

In [8]:
np.random.rand(5,2)

array([[0.80382338, 0.53929812],
       [0.26802575, 0.20946015],
       [0.07946227, 0.99774042],
       [0.24810667, 0.91662537],
       [0.86461668, 0.33061907]])

In [9]:
np.random.randint(0, 101, 10)

array([60, 59, 98, 14, 58, 34, 90, 74, 79, 10])

## Setting seed allows us to get same results

In [10]:
np.random.seed(100)
np.random.rand(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

  ## Modifying shapes

In [14]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr = np.random.randint(0,101,10)

In [21]:
ranarr

array([58, 16,  9, 93, 86,  2, 27,  4, 31,  1])

In [22]:
ranarr.max()

93

In [23]:
ranarr.min()

1

In [25]:
ranarr.argmax()

3

In [26]:
ranarr.dtype

dtype('int32')

In [27]:
ranarr.shape

(10,)